# Generated by Django 4.0 on 2024-11-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookapp', '0002_alter_step_description_alter_step_step_number'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='step',
            constraint=models.UniqueConstraint(fields=('recipe', 'step_nmber'), name='unique_step_per_recipe'),
        ),
    ]
